version: '3'

env:
  SDK_IMAGE: 5keeve/pocketbook-go-sdk:6.3.0-b288-v1
  APP_NAME: pb-dropbox-downloader.app
  UI_ENTRYPOINT: cmd/ui/main.go
  CLI_ENTRYPOINT: cmd/cli/main.go
  VERSION:
    sh: git describe
  LDFLAGS: -ldflags="-X pb-dropbox-downloader/internal/app.version={{ .VERSION  | upper }} -s -w"

tasks:
  default:
    cmds:
      - task: run

  run: go run {{.LDFLAGS}} -tags=debug {{ .CLI_ENTRYPOINT }}
  run:rm:
    cmds:
      - task: run
      - rm -rf ./testing/testdata/internal/dropbox

  build:debug:
    cmds:
      - go build -tags=debug {{.LDFLAGS}} -o {{.APP_NAME}} {{.CLI_ENTRYPOINT}}

  build:internal: docker run --rm -v ${PWD}:/app {{.SDK_IMAGE}} build -v {{.LDFLAGS}} -o {{.APP_NAME}} /app/{{.ENTRYPOINT}}

  build:ci:
    cmds:
      - go build {{.LDFLAGS}} -o {{.APP_NAME}} {{.CLI_ENTRYPOINT}}

  build:
    deps:
      - task: build:internal
        vars:
          ENTRYPOINT: '{{.UI_ENTRYPOINT}}'

  build:cli:
    deps:
      - task: build:internal
        vars:
          ENTRYPOINT: '{{.CLI_ENTRYPOINT}}'

  lint-local: golangci-lint run ./...

  test-local: go test ./internal/...

  test:ci: go test -cover -coverprofile='coverage.xml' -covermode=atomic -v ./internal/...

  test: docker run --rm -it -v ${PWD}:/app golang:1.17.2 bash -c "cd /app; go test -cover -v ./internal/..."
