version: '3'

tasks:
  default: go run .

  build: 
    env:
      GOOS: linux
      GOARCH: arm
      GOARM: 5
    cmds:
      - go build -ldflags="-s -w" -o pb-dropbox-downloader.app .

  test: go test ./...
