name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Taskfile
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        version: '3.10.0'

    # - name: Lint
    #   uses: golangci/golangci-lint-action@v3
    #   with:
    #     version: latest

    - name: Build
      run: task build:ci

    - name: Test
      run: task test:ci

    - name: Upload coverage profile
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-pb-dropbox-downloader
        fail_ci_if_error: true
        verbose: true
